export type Product = {
  id: string;
  name: string;
  description: string;
  price: number; // Price in cents (0 for FREE)
  category: 'lesson-plan' | 'worksheet' | 'decor' | 'bundle';
  image: string;
  tptUrl: string;
  isFree?: boolean;
  featured?: boolean;
};

// TPT Store URL
export const TPT_STORE_URL = 'https://www.teacherspayteachers.com/store/elementary-state-of-mind';

export const products: Product[] = [
  {
    id: 'space-case-complete',
    name: 'Space Case Complete Novel Study & PBL',
    description: 'Everything you need to teach Space Case from engagement to evaluation — in ONE bundle. This ultimate Space Case bundle combines a high-engagement Mock Trial PBL with a ready-to-use novel assessment.',
    price: 1120,
    category: 'bundle',
    image: '/products/space-case-complete.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Space-Case-Complete-Novel-Study-PBL-15118510',
    featured: true,
  },
  {
    id: 'space-case-mock-trial',
    name: 'Space Case Mock Trial',
    description: 'Turn your novel study into a courtroom drama your students will NEVER forget. This low-prep, high-engagement Mock Trial + PBL transforms Stuart Gibbs\' Space Case into an immersive courtroom experience.',
    price: 1200,
    category: 'lesson-plan',
    image: '/products/space-case-mock-trial.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Space-Case-Mock-Trial-15118462',
  },
  {
    id: 'any-text-debate',
    name: 'Any Text Debate Prep Tool',
    description: 'Develop evidence-based reasoning skills through structured debate preparation. Supports CER, OREO, and RACES frameworks with teacher guide, prep pages, and both printable and digital formats. Perfect for grades 3–8.',
    price: 400,
    category: 'lesson-plan',
    image: '/products/any-text-debate.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Any-Text-Debate-Prep-Tool-15122470',
  },
  {
    id: 'ela-anchor-charts',
    name: 'ELA Anchor Chart Printables (Hand-Drawn)',
    description: 'Brighten up your ELA block with engaging, hand-drawn anchor charts that make essential skills stick! This set includes 9 beautifully illustrated, student-friendly charts—perfect for interactive notebooks.',
    price: 500,
    category: 'worksheet',
    image: '/products/ela-anchor-charts.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/ELA-Anchor-Chart-Printables-Hand-Drawn-Interactive-Notebook-14923275',
  },
  {
    id: 'oreo-opinion-writing',
    name: 'OREO Opinion Writing',
    description: 'Make teaching opinion writing simple, structured, and engaging with this complete OREO (Opinion, Reason, Example/Explanation, Opinion restated) writing resource. Differentiated graphic organizers for Grades 3–6.',
    price: 500,
    category: 'worksheet',
    image: '/products/oreo-opinion-writing.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/OREO-Opinion-Writing-14923127',
    featured: true,
  },
  {
    id: 'kpop-demonhunters',
    name: 'Behind the Beat: KPop DemonHunters',
    description: 'Turn your classroom into a high-energy music, film, and critical thinking hub with this engaging, standards-aligned resource designed for elementary learners (Grades 2–6).',
    price: 500,
    category: 'lesson-plan',
    image: '/products/kpop-demonhunters.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Behind-the-Beat-KPop-DemonHunters-14864201',
  },
  {
    id: 'math-notes-fractions',
    name: '5th/6th Grade 4-Square Math Notes - Fractions & Decimals',
    description: 'Support your students with clear, visual, step-by-step fraction and decimal instruction using these hand-drawn 4-square math anchor charts and practice pages.',
    price: 400,
    category: 'worksheet',
    image: '/products/math-notes-fractions.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/5th6th-Grade-4-Square-Math-Notes-Hand-Drawn-Fractions-Decimals-14923373',
  },
  {
    id: 'informative-essay-packet',
    name: 'Informative 5 Paragraph Essay Writing Packet',
    description: 'Complete packet with writing prompts, sentence starters, rubric, and student packet including brain dump page, tree map graphic organizer, 5 paragraph essay outline, and lined paper.',
    price: 400,
    category: 'bundle',
    image: '/products/informative-essay-packet.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Informative-5-Paragraph-Essay-Writing-Packet-12548089',
  },
  {
    id: 'opinion-essay-packet',
    name: 'Opinion 5 Paragraph Essay Writing Packet',
    description: 'Complete packet with opinion essay writing prompts, sentence starters, rubric, and student packet including brain dump page, tree map graphic organizer, 5 paragraph essay outline, and lined paper.',
    price: 400,
    category: 'bundle',
    image: '/products/opinion-essay-packet.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Opinion-5-Paragraph-Essay-Writing-Packet-12548373',
  },
  {
    id: 'narrative-writing-packet',
    name: 'Narrative Writing Packet',
    description: 'Step-by-step graphic organizers to help beginning and intermediate-grade writers. Includes narrative writing prompts, sentence starters, rubric, and student packet with various graphic organizers.',
    price: 400,
    category: 'bundle',
    image: '/products/narrative-writing-packet.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Narrative-Writing-Packet-12544887',
  },
  {
    id: 'article-a-week',
    name: 'Article-A-Week: Endangered Species',
    description: 'Weekly 20-30-minute independent activity for students to practice reading and responding to informational text. Includes 10 articles about endangered species with reading comprehension questions.',
    price: 400,
    category: 'lesson-plan',
    image: '/products/article-a-week.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Article-A-Week-Endangered-Species-12783324',
  },
  {
    id: 'slc-guide',
    name: 'Student-Led Conference (SLC) Guide',
    description: 'Complete packet with student-led conference guide, teacher guide with suggestions and prep materials, plus parent reflection and sign-in sheet.',
    price: 400,
    category: 'lesson-plan',
    image: '/products/slc-guide.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Student-Led-Conference-SLC-Guide-12548739',
  },
  {
    id: 'friendsgiving',
    name: 'Friendsgiving Potluck & Gratitude Toasts',
    description: 'Bring warmth, gratitude, and community into your classroom with this meaningful activity—a meaningful way to celebrate friendship, reflection, and togetherness. Perfect for grades 3–8.',
    price: 200,
    category: 'lesson-plan',
    image: '/products/friendsgiving.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Friendsgiving-Potluck-Gratitude-Toasts-14883372',
  },
  {
    id: 'space-case-test',
    name: 'Space Case End of Book Test',
    description: 'Check comprehension and critical thinking with this ready-to-print, standards-aligned assessment for Space Case by Stuart Gibbs. Perfect for Grades 5–6.',
    price: 200,
    category: 'worksheet',
    image: '/products/space-case-test.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Space-Case-by-Stuart-Gibbs-End-of-Book-Test-14883681',
  },
  {
    id: '67th-day',
    name: '67th Day of School Activities',
    description: '67 Word Stories + 6–7 Minute Math + Certificates. Make the 67th day of school a day your students won\'t forget with this fun, low-prep, high-engagement mini-bundle! Perfect for grades 5–7.',
    price: 67,
    category: 'bundle',
    image: '/products/67th-day.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/67th-Day-of-School-Activities-14863736',
    featured: true,
  },
  {
    id: 'opinion-tree-map',
    name: 'Opinion Essay Tree Map Graphic Organizer',
    description: 'Graphic organizer for students to plan out their opinion writing. Tree map with space for opinion statement, reasons, and supporting details.',
    price: 100,
    category: 'worksheet',
    image: '/products/opinion-tree-map.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Opinion-Essay-Tree-Map-Graphic-Organizer-12548363',
  },
  {
    id: 'story-elements',
    name: 'Story Elements Graphic Organizer',
    description: 'Helps students organize and sequence the events in their narrative writing. Includes spaces for characters, setting, problem, events, and solution.',
    price: 100,
    category: 'worksheet',
    image: '/products/story-elements.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Story-Elements-Graphic-Organizer-12544994',
  },
  {
    id: 'informative-tree-map',
    name: 'Informative Essay Tree Map Graphic Organizer',
    description: 'Graphic organizer for students to plan out their informative writing. Tree map with space for topic, main ideas, and supporting details.',
    price: 100,
    category: 'worksheet',
    image: '/products/informative-tree-map.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Informative-Essay-Tree-Map-Graphic-Organizer-12548206',
  },
  {
    id: 'seven-minute-strategy',
    name: 'Seven-Minute-Strategy Share Out Tool',
    description: 'Template for teachers to share strategies, best practices, or classroom management techniques during staff meetings, PLC time, or collaboration sessions.',
    price: 100,
    category: 'lesson-plan',
    image: '/products/seven-minute-strategy.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Seven-Minute-Strategy-Share-Out-Tool-for-Staff-Meetings-PLC-or-Collab-13055750',
  },
  {
    id: 'student-work-posters',
    name: 'Student Work Coming Soon Posters',
    description: 'Printable posters designed for hanging in lieu of student work at the beginning of the year or anytime you need a placeholder for bulletin boards.',
    price: 100,
    category: 'decor',
    image: '/products/student-work-posters.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Student-Work-Coming-Soon-Posters-5546460',
  },
  {
    id: 'plot-diagram',
    name: 'Plot Diagram Graphic Organizer',
    description: 'Helps students organize and sequence the events in their narrative writing using exposition, rising action, climax, falling action, and resolution.',
    price: 100,
    category: 'worksheet',
    image: '/products/plot-diagram.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Plot-Diagram-Graphic-Organizer-12544974',
  },
  {
    id: 'plant-posters',
    name: 'Student Work Coming Soon Plant Posters',
    description: 'Plant-themed printable posters designed for hanging in lieu of student work at the beginning of the year or anytime you need a placeholder.',
    price: 100,
    category: 'decor',
    image: '/products/plant-posters.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Student-Work-Coming-Soon-Plant-Posters-12544182',
  },
  {
    id: 'letter-to-teacher',
    name: 'Letter to my Teacher',
    description: 'FREE letter template - printable or digital. Students can write a letter to their teachers past, present, or future. Great end of year, beginning of year, or holiday activity.',
    price: 0,
    category: 'worksheet',
    image: '/products/letter-to-teacher.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Letter-to-my-Teacher-5546447',
    isFree: true,
    featured: true,
  },
  {
    id: 'goal-setting-bingo',
    name: '2025 Goal Setting BINGO',
    description: 'FREE printable BINGO card and Google slideshow for students to set and track their 2025 goals. A fun, interactive way to start the new year!',
    price: 0,
    category: 'worksheet',
    image: '/products/goal-setting-bingo.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/2025-Goal-Setting-BINGO-12778057',
    isFree: true,
  },
  {
    id: 'opinion-brain-dump',
    name: 'Opinion Essay Brain Dump Graphic Organizer',
    description: 'FREE space for students to jot down ideas and complete an initial brainstorm before writing their opinion essay.',
    price: 0,
    category: 'worksheet',
    image: '/products/opinion-brain-dump.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Opinion-Essay-Brain-Dump-Graphic-Organizer-12548286',
    isFree: true,
  },
  {
    id: 'essay-brain-dump',
    name: 'Essay Brain Dump Graphic Organizer',
    description: 'FREE space for students to jot down ideas and complete an initial brainstorm before writing their essay.',
    price: 0,
    category: 'worksheet',
    image: '/products/essay-brain-dump.jpg',
    tptUrl: 'https://www.teacherspayteachers.com/Product/Essay-Brain-Dump-Graphic-Organizer-12548189',
    isFree: true,
  },
];
